# -*- coding: utf-8 -*-
"""No6_Single Responsibility Principle_UAS PBO.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rREJJQN_Jl6B_xazsMlM4nzoJQFtUF6i
"""

# Single Responsibility Principle (SRP)

# Contoh salah:
class PaymentProcessor:
    def __init__(self, payment_method):
        self.payment_method = payment_method
        
    def process_payment(self, amount):
        # Proses pembayaran menggunakan payment_method
        pass
    
    def send_email_receipt(self, email):
        # Kirim email dengan struk pembayaran
        pass
    
# Contoh benar:
class PaymentProcessor:
    def __init__(self, payment_method):
        self.payment_method = payment_method
        
    def process_payment(self, amount):
        # Proses pembayaran menggunakan payment_method
        pass
    
class EmailSender:
    def send_email(self, email, receipt):
        # Kirim email dengan struk pembayaran
        pass