# -*- coding: utf-8 -*-
"""No6_Dependency Inversion Principle_UAS PBO.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jtQGLwUILaPYRYotLPwmIQ9pKtIvuijf
"""

# Dependency Inversion Principle (DIP)

class FileReader:
    def read(self, file_name):
        with open(file_name, "r") as f:
            return f.read()

class CSVReader:
    def __init__(self, file_reader):
        self.file_reader = file_reader
    
    def read_csv(self, file_name):
        data = self.file_reader.read(file_name)
        lines = data.split("\n")
        return [line.split(",") for line in lines]

class PDFReader:
    def __init__(self, file_reader):
        self.file_reader = file_reader
    
    def read_pdf(self, file_name):
        # PDF reading logic here
        pass

# Using dependency injection
file_reader = FileReader()
csv_reader = CSVReader(file_reader)
pdf_reader = PDFReader(file_reader)

# Atau dengan menggunakan abstract class atau interface sebagai abstraction:

class FileReaderInterface:
    def read(self, file_name):
        pass

class FileReader(FileReaderInterface):
    def read(self, file_name):
        with open(file_name, "r") as f:
            return f.read()

class CSVReader:
    def __init__(self, file_reader: FileReaderInterface):
        self.file_reader = file_reader
    
    def read_csv(self, file_name):
        data = self.file_reader.read(file_name)
        lines = data.split("\n")
        return [line.split(",") for line in lines]

class PDFReader:
    def __init__(self, file_reader: FileReaderInterface):
        self.file_reader = file_reader
    
    def read_pdf(self, file_name):
        # PDF reading logic here
        pass

# Using abstract class or interface as abstraction
file_reader = FileReader()
csv_reader = CSVReader(file_reader)
pdf_reader = PDFReader(file_reader)

# Dengan demikian, kelas CSVReader dan PDFReader 
# tidak tergantung pada kelas FileReader secara langsung, 
# tapi hanya tergantung pada interface FileReaderInterface. 
# Ini sesuai dengan prinsip DIP.